version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '18080:8080'
      - '4566:4566'
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs,sns,events,ssm

  create_localstack_resources:
    image: anigeo/awscli
    entrypoint: '/root/localstack/create_localstack_resources.sh'
    volumes:
      - .:/root
    depends_on:
      - localstack
