service: email-service
frameworkVersion: '3'
projectDir: ..

plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-slic-watch-plugin
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region}
  sesRegion: ${self:custom.sesRegions.${self:provider.region}, 'us-east-1'}
  tracing:
    lambda: true
  environment:
    SLIC_STAGE: ${self:provider.stage}
    SES_REGION: ${self:provider.sesRegion}
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221

custom:
  app: ${file(../../app.yml)}
  bundle:
    esbuild: true
    linting: false
  emailQueueName: ${self:provider.stage}-email-queue
  prune:
    automatic: true
  number: 3
  sesRegions:
    us-east-1: us-east-1
    us-west-2: us-west-2
    eu-west-1: eu-west-1
  serverless-offline:
    httpPort: 4003
    lambdaPort: 4005
    websocketPort: 4004
    stage: local
  serverless-offline-sqs:
    endpoint: ${env:SQS_ENDPOINT_URL,'http://0.0.0.0:4576'}
    autoCreate: true
    region: ${self:provider.region}
  slicWatch: ${self:custom.app.slicWatch}

functions: ${file(./sls-functions.yml)}

resources:
  Resources:
    emailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.emailQueueName}
