name: docs-build-release
on:
  push:
    branches:
      - main
concurrency: ci-${{ github.ref}}-${{ github.event_name }}
env:
  NODE_VERSION: 16
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/cache@v3
      with:
        path: |
          packages/docs-build/build
        key: ${{ github.sha }}-build
    - name: install
      run: npm exec --workspace packages/docs-build --call "npm ci"
    - name: build docs
      run: npm run build --workspace packages/docs-build
  docs-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            packages/docs-build/build
          key: ${{ inputs.commit }}-docs-release
          restore-keys: |
            ${{ github.sha }}-build
            ${{ github.sha }}-docs-release
      - name: Release to GH pages on main
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: packages/docs-build/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
